// QC v2 — critical rule IDs. Any one = NOT SELLABLE.

export const CRITICAL_RULE_IDS = [
  "TEXT_OVERFLOW",
  "TEXT_CLIPPED",
  "TEXT_OUTSIDE_SAFE_AREA",
  "MISSING_PAGE",
  "BLANK_UNINTENDED_PAGE",
  "BROKEN_FONT_OR_GLYPH",
  "IMAGE_MISSING",
  "IMAGE_PLACEHOLDER",
  "INVALID_PDF",
  "FAKE_PDF_MIME_TYPE",
  "UNREADABLE_TEXT",
  "COVER_TITLE_MISMATCH",
  "CHARACTER_IDENTITY_BREAK",
  "WRONG_LANGUAGE",
  "COPYRIGHT_PLACEHOLDER",
  "DUPLICATED_PAGE",
  "PAGE_ORDER_ERROR",
  "CONTENT_UNSAFE_FOR_AGE",
  "INTERIOR_ILLUSTRATIONS_MISSING",
  "DUPLICATE_ILLUSTRATION_DETECTED",
  "THUMBNAIL_MISSING",
  "PREVIEW_PAGES_MISSING",
  "COVER_MISSING",
  "STYLE_BIBLE_MISSING",
  "PDF_GLYPH_MANGLING",
  "VISION_CHARACTER_CONSISTENCY_FAIL",
  "VISION_COVER_INTERIOR_MISMATCH",
  "VISION_STYLE_BIBLE_MISMATCH",
  "STORY_AGE_APPROPRIATENESS",
  "STORY_COHERENCE",
  "STORY_EMOTIONAL_PAYOFF",
  "STORY_REREAD_VALUE",
  "STORY_LANGUAGE_LEVEL",
  "STORY_PARENT_BUYER_VALUE",
  "STORY_GENERIC_RISK_HIGH",
  "KIDS_MEASURED_QC_MISSING",
] as const;

export type CriticalRuleId = (typeof CRITICAL_RULE_IDS)[number];

export function isCritical(ruleId: string): boolean {
  return (CRITICAL_RULE_IDS as readonly string[]).includes(ruleId);
}
