INSERT INTO public.pipeline_skills (skill_key, version, source, target_dimension, content_md, metadata)
VALUES (
  'kids_branding',
  1,
  'seed',
  'kids_branding',
  $md$
# kids_branding v1

Applies to every kids picture book AND coloring book at build time.
Existing live books receive branding on their next rebuild — never
force-rebuild retroactively.

## Corner layout (interior pages)

- bottom-right: Official SecretPDF Kids footer logo, image, 13% page width, min 72pt. Skipped when the corner is too dark, too bright, or too busy (see heuristic).
- bottom-left: `(c) secretpdf.co`, Helvetica 8pt warm-ink on translucent cream panel. Only suppressed on catastrophic contrast (dark AND noisy).

## Skip heuristic (story pages only)

Sample bottom-right 25% x 25% region of the underlying illustration:
- mean < 45  -> skip logo (corner_too_dark)
- mean > 245 -> skip logo (corner_too_bright)
- variance > 3500 -> skip logo (corner_too_busy)
- mean < 20 AND variance > 1500 -> also skip copyright

## Non-negotiables

- Cover NEVER has corner branding.
- Title / copyright / bonus / closing pages ALWAYS have branding.
- Logo is NEVER baked into AI-generated illustrations; the layout engine stamps it. The image prompt continues to forbid text.
- Logo may not overlap caption text or the subjects face.

## QC extension

`qc_scorecard.branding_qc` records per-page `{ logo, copyright, reason, page_kind, page_index, corner? }`. `summary.logo_skipped_pages` and `summary.copyright_skipped_pages` list any aesthetic-exception omissions. QC gate: every skipped page must have a recorded `reason` (no silent drops).

## Assets

The three canonical CDN URLs live in `src/lib/kidsBranding.ts` under `KIDS_BRAND_ASSETS`. The uploaded owner asset (2172x724 PNG) is NEVER regenerated by any AI model.
  $md$,
  jsonb_build_object(
    'asset_urls', jsonb_build_object(
      'full',   '/__l5e/assets-v1/dd11326e-a17c-44fe-bc4b-e12316d162ec/secretpdf-kids-logo.png',
      'footer', '/__l5e/assets-v1/f42163b0-0dc9-44a2-b7ef-518b2f925ab5/secretpdf-kids-logo-footer.png',
      'mark',   '/__l5e/assets-v1/871ef258-5c41-4fd9-bb5f-57f03f6b742e/secretpdf-kids-mark.png'
    ),
    'layout', jsonb_build_object(
      'logo_frac', 0.13,
      'logo_min_pt', 72,
      'safe_margin_pt', 24,
      'copyright_pt', 8,
      'copyright_text', '(c) secretpdf.co'
    ),
    'skip_heuristic', jsonb_build_object(
      'sample_region', 'bottom_right_25pct',
      'logo_dark_max_mean', 45,
      'logo_bright_min_mean', 245,
      'logo_busy_max_variance', 3500,
      'copyright_dark_mean', 20,
      'copyright_noisy_variance', 1500
    ),
    'applies_to', jsonb_build_array('picture_book', 'coloring_book'),
    'immutability_note', 'Owner-supplied 2172x724 PNG asset — NEVER AI-regenerated.'
  )
)
ON CONFLICT (skill_key, version) DO UPDATE
SET content_md = EXCLUDED.content_md,
    metadata   = EXCLUDED.metadata,
    updated_at = now();