ALTER TABLE public.generation_settings
  ADD COLUMN IF NOT EXISTS category_mix JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS auto_rewrite_limit INTEGER NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS shopify_draft_upload_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS paused BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS per_ebook_budget_usd NUMERIC(10,2) NOT NULL DEFAULT 2.00;
